/* Easter egg 🌷 — unlocked from the egg on the dashboard. Edit freely. */

/** Only this date of birth unlocks the surprise (1 November 2003). */
export const SECRET_DOB = '2003-11-01';

export const HER_NAME = 'Sreekutty';

export const QUESTION = 'Will you be mine, forever?';

/** One note per day — a new one shows up every day, then the list starts over. */
export const LOVE_NOTES: string[] = [
  'You are the best thing that has ever happened to my life. Nothing else even comes close.',
  'Before you, I didn’t know a heart could feel this full. Now mine overflows every single day.',
  'If I had to choose between breathing and loving you, I would use my last breath to say I love you.',
  'You walked into my life and suddenly everything made sense.',
  'Every love song I hear now is secretly about you.',
  'I don’t need a lucky charm. I have you, and that is more luck than I deserve.',
  'Your smile is my favourite place in the whole world.',
  'In a room full of people, my eyes will always look for you.',
  'You are my today and every one of my tomorrows.',
  'I fall for you a little more every day — even on the days I think that’s impossible.',
  'Home isn’t a place anymore. Home is wherever you are.',
  'You are the answer to every prayer I never knew I was making.',
  'I would choose you in every lifetime, in every world, in every version of me.',
  'The best part of my day is any part with you in it.',
  'You make ordinary moments feel like magic.',
  'My heart was a quiet place until you came and filled it with music.',
  'I love you more than yesterday, and less than I will tomorrow unda kanniii.',
  'You are my calm in every storm vaveee and my sunshine on every grey day 💋.',
  'Of all the beautiful things in this world, you are my favourite vava 😘.',
  'If kisses were stars, I would give you the whole sky 🙈.',
  'Thank you for being you — the kindest, loveliest, most wonderful person I know.',
  'Loving you is the easiest thing I have ever done.',
  'You are my best friend, my peace, my happiness and my forever.',
  'When I count my blessings, I count you twice. 🙈 Thookiyalloo naadhaaa🙈',
  'I didn’t believe in fairy tales until I met you. hehehe',
  'You are the reason I smile at my phone like a fool.',
  'Shoo Every time I see you, I fall in love all over again. nte oorkum nte kutti nth sundari aane nn',
  'With you, I have everything. Without you, nothing feels complete. shoo paavam njan',
  'You hold my heart in your hands — and there is nowhere safer for it to be.',
  'If I could give you one thing, it would be the ability to see yourself through my eyes. Then you’d know how special you are.',
  'Nte favourite fairy tale is our love story.',
  'You make me want to be a better person, every single day.',
  'I love the way you laugh, the way you think, the way you are. I love all of you.',
  'Nte vava aane my sweetest dream that came true.',
  'No matter where life takes us, my heart will always find its way back to you.',
  'You are not just the love of my life — you are my life.',
  'Like tulips that open for the sun, my heart opens only for you. 🌷',
  'Some people search their whole life for what I found in you.',
  'Being yours is my favourite thing to be.',
  'Today, tomorrow and always — it’s you. It will always be you.',

  // longer notes
  'Some days I just sit and think about how lucky I am. Out of every person in this whole wide world, you chose me. I don’t know what I did to deserve that, but I promise to spend every day trying to be worthy of it.',
  'Before you came into my life, I thought I knew what happiness was. Then you smiled at me, and I realised I had only been living in black and white. You brought all the colours with you.',
  'If someone asked me what the best thing that ever happened to me is, I wouldn’t have to think for even a second. It’s you. It has always been you, and it will always be you.',
  'I love you not only for who you are, but for who I become when I am with you. You make me kinder, braver and happier than I ever knew I could be.',
  'When I am tired, you are my rest. When I am lost, you are my way home. When I am sad, you are the reason I smile again. You are simply everything to me.',
  'I don’t need grand adventures or faraway places. Give me a quiet evening, a cup of chai and you sitting next to me, and I will have everything my heart could ever want.',
  'There are moments when I look at you and my heart feels so full it almost hurts. That’s what you do to me — you fill every empty corner of my heart with love.',
  'I want you to know that on your worst day, I will still choose you. On your messiest, saddest, most tired day, I will still look at you and think, how did I get so lucky?',
  'You walked into my life like sunlight through a window — quietly, softly, and suddenly everything was warm and bright. I never want to close the curtains again.',
  'If I could give you anything in the world, I would give you the ability to see yourself the way I see you. Then you would finally understand how rare and precious you are.',
  'My favourite thing in the world is the way you say my name. It sounds like home, like safety, like love. I could hear it a million times and never get tired of it.',
  'People say love fades with time, but with you it only grows. Every single day I find a new reason to love you, and every single day I love you more than the day before.',
  'I used to wonder why things never worked out before. Now I know — life was saving my heart for you. Every wrong turn was leading me straight to the right person.',
  'You are the first thought in my mind when I wake up and the last one before I fall asleep. In between, you are in every little moment of my day, even when you don’t know it.',
  'Thank you for loving me in ways I didn’t even know I needed. Thank you for your patience, your laughter and your gentle heart. My life is so much more beautiful because you are in it.',
  'If loving you were a job, I would never take a single day off. I would work overtime, weekends and holidays, and I would still feel like the luckiest person alive.',
  'When I imagine my future, I don’t see big houses or fancy cars. I see your face across the breakfast table, your hand in mine on long walks, and your laugh filling every room of our home.',
  'You don’t have to do anything special to make me happy. Just being you is enough. Your presence alone turns my ordinary days into the best days of my life.',
  'I have seen many beautiful things in my life — sunsets, oceans, starry skies — but nothing has ever taken my breath away the way you do, every single time I look at you.',
  'There is nobody in this world I would rather laugh with, cry with, dream with and grow old with. You are my person, my partner and my forever.',
  'You came into my life when I least expected it, and you changed everything. Now I can’t imagine a single day without you, and I never want to try.',
  'When the world feels too loud, your voice is the only thing that calms me down. When everything feels uncertain, you are the one thing I’m completely sure of.',
  'I promise to love you on the days you love yourself and especially on the days you don’t. I will always remind you how amazing you are until you believe it too.',
  'Some people spend their whole lives searching for the kind of love we have. I found it in you, and I will hold on to it with everything I have.',
  'If I had a flower for every time you made me smile, I would be standing in an endless field of tulips. 🌷 That’s how much joy you have brought into my life.',
  'You are not just my love — you are my best friend, my biggest supporter, my favourite person to talk to and the one I want to share every little piece of my life with.',
  'I love the little things about you that nobody else notices — the way you get excited about small things, the way you care so deeply, the way your eyes light up when you laugh.',
  'I know I am not perfect, and I know I will make mistakes. But I promise you one thing: my love for you will never be one of them. Loving you is the best thing I have ever done.',
  'Every love story is beautiful, but ours is my favourite. Not because it is perfect, but because it is ours — full of laughter, little fights, sweet makeups and endless love.',
  'If you ever forget how special you are, come back to this page. I will keep reminding you every single day that you are the best thing that has ever happened to me.',
  'With you, I feel like I can finally breathe. No masks, no pretending, no trying to be someone else. Just me, loved exactly as I am, by the most wonderful person I know.',
  'I would cross oceans, climb mountains and walk through every storm just to see you smile. And honestly, I would do it all again tomorrow without thinking twice.',
  'The day you came into my life, my heart finally understood what it had been waiting for. It was you all along — it was always meant to be you.',
  'You make me believe in all the things I used to think only happened in movies — love at first sight, soulmates, and happily ever after. You are my happily ever after.',
  'When I hold your hand, the whole world feels right. All my worries fade away, and nothing else matters except the feeling of your fingers wrapped around mine.',
  'I hope you know that you are loved — not a little, not sometimes, but completely and endlessly, every second of every day. Nothing will ever change that.',
  'If I could go back in time, I would find you sooner so I could love you longer. Every day before we met feels like a day I missed out on.',
  'You have this magical way of making everything better. A bad day becomes bearable, a good day becomes perfect, and a normal day becomes one I will remember forever.',
  'Every time you laugh, I fall a little deeper. Every time you look at me, my heart skips a beat. Every time you say you love me, I feel like the luckiest person on earth.',
  'No matter how busy life gets, no matter how far apart we might be, I want you to know you are always on my mind and forever in my heart.',
  'I don’t want a perfect life. I want a real life with you — with lazy mornings, silly jokes, long talks, little arguments and a love that keeps getting stronger.',
  'You are the reason I look forward to tomorrow. You are the reason I smile for no reason. You are the reason my heart feels so full. You are my reason for everything.',
  'They say home is where the heart is. My heart is with you, so wherever you are, that is where I belong. You are my home, now and always.',
  'I fell in love with you slowly, and then all at once. And now I find myself falling again every single day, a little more each time, with no plans of ever stopping.',
  'If I wrote down every reason I love you, I would never stop writing. There would be no paper left in the world, and I would still have so much more to say.',
  'Your love is like a warm blanket on a cold night — soft, comforting and the only place I ever want to be. Thank you for wrapping my heart in so much warmth.',
  'You are the most beautiful person I know, inside and out. Your heart is kind, your soul is gentle, and your smile could light up the darkest night.',
  'Every moment with you is a gift. Even the quiet ones, even the simple ones, even the ones where we do nothing at all. Especially those ones.',
  'I don’t know what the future holds, but I know I want you in it. Every plan, every dream, every tomorrow I imagine has you right there beside me.',
  'When I look back at my life one day, the part I will be most grateful for is the part where I met you. You turned my whole story into a love story.',
  'Loving you feels like the most natural thing in the world, like breathing or the sun rising in the morning. It is not something I try to do — it is just who I am now.',
  'You are my calm on chaotic days, my sunshine on gloomy days and my favourite thought on every day. I am so grateful that life led me to you.',
  'I want to be the reason you smile when you look at your phone. I want to be the reason you feel safe. I want to be the person you never have to doubt.',
  'Even if I had a thousand lives, I would spend every single one of them looking for you. And when I found you, I would fall in love with you all over again.',
  'Your happiness means more to me than my own. Seeing you smile is the best reward I could ever ask for, and I will spend my life trying to keep that smile on your face.',
  'The best feeling in the world is knowing that someone as amazing as you loves me back. Some days I still can’t believe it’s real.',
  'You are my favourite hello and my hardest goodbye. Every time we part, I count the minutes until I see you again, and every reunion feels like the first time.',
  'I love how you understand me without me saying a word. I love how you know when something is wrong. I love how you always know exactly what to say to make it better.',
  'There is no version of my future that I would want without you. You are not just part of my plans — you are the most important part of them.',
  'If I could hold one moment forever, it would be any moment with you — your head on my shoulder, your laugh in my ears, and your hand holding mine.',
  'Life is full of ups and downs, but with you by my side, I know I can get through anything. You make me stronger than I ever thought I could be.',
  'You are the kind of beautiful that makes the world stop for a second. Not just your face, but your heart, your kindness and the way you care for everyone around you.',
  'I love you for all the big things — your kindness, your strength, your heart. And I love you for all the small things — your little habits, your silly jokes and your sleepy face.',
  'Whenever I feel lost, I just think of you, and suddenly I know exactly where I am meant to be. You are my compass, my anchor and my safe place.',
  'My heart has never felt as safe as it does with you. You hold it so gently, so carefully, like it is the most precious thing in the world. And to you, I hope it is.',
  'Some people make you feel loved. You make me feel cherished, understood and seen in ways I never knew were possible. Thank you for loving me so beautifully.',
  'You deserve flowers every day, love letters every night and someone who tells you how amazing you are every single moment. I want to be that someone for you, always.',
  'I may not always find the right words, but I hope you can feel it — in every look, every hug, every little thing I do. All of it says I love you.',
  'When I think about everything I am thankful for, you are always at the very top of the list. You are my biggest blessing and my sweetest gift.',
  'I want to spend my whole life making you feel as special as you make me feel. Even that would not be enough to show you how much you mean to me.',
  'You are the poetry I never knew how to write, the song I always wanted to sing and the dream I never want to wake up from. You are my everything.',
  'If tomorrow is uncertain and the world keeps changing, one thing will always stay the same: my love for you. That is the one promise I will never break.',
  'Being with you feels like summer evenings, warm chai on rainy days and the first bloom of spring all at once. You make every season of my life beautiful.',
  'I never believed in soulmates until I met you. Now I know that some souls are simply meant to find each other, and mine was always meant to find yours.',
  'Thank you for every time you listened, every time you understood, every time you forgave and every time you loved me even when I didn’t make it easy.',
  'You are the most important person in my life. Not because I have to say it, but because every part of my heart knows it is true.',
  'In a world full of temporary things, you are my forever. In a life full of questions, you are my answer. In a heart full of dreams, you are the biggest one.',
  'When I see you happy, my whole world lights up. When I see you sad, I would do anything to take that pain away. Your heart is my heart now.',
  'Out of all the moments in my life, the ones I treasure most are the simple ones with you — talking for hours, laughing at nothing and just being together.',
  'You have no idea how many times a day I think about you and smile. If you could see inside my heart, you would find your name written on every single page.',
  'I want to wake up every morning knowing you are mine and go to sleep every night grateful that I am yours. That is my idea of a perfect life.',
  'Some love stories are loud and dramatic. Ours is soft, quiet and steady — the kind of love that grows deeper every day, like the roots of a tree that will never fall.',
  'You didn’t just steal my heart — you made it better. You fixed the broken pieces, filled the empty spaces and taught it how to love without fear.',
  'If I had to describe you in one word, I couldn’t. You are too many beautiful things at once — kind, funny, strong, gentle, smart and absolutely lovely.',
  'Even on the hardest days, knowing that you are in my life makes everything worth it. You are the light at the end of every tunnel I walk through.',
  'When we are old and grey, I still want to hold your hand, steal your blanket, make you laugh and tell you every day that you are the love of my life.',
  'There is something about you that makes my heart feel calm and excited at the same time. Maybe that’s what true love feels like — peace and butterflies, all at once.',
  'You are the best part of every day, the sweetest part of every memory and the brightest part of every dream. I love you more than words will ever say.',
  'I am not asking for forever all at once. I just want today with you, and then tomorrow, and then the day after that — until all those days add up to forever.',
  'Every tulip on this page is a tiny piece of my heart falling for you. 🌷 And just like these tulips, my love for you will never stop.',
  'You light up every room you walk into, but more than that, you light up my whole life. Before you, I didn’t even know how dark it was.',
  'I could spend hours just looking at you and still find something new to love — the way you think, the way you smile, the way you make the world a little gentler.',
  'I want you to remember this on days you feel unseen: someone out here thinks you are the most wonderful person in the world. That someone is me, and it always will be.',
  'Love is not just a feeling for me anymore — it is a choice I make every single day. And every single day, without a doubt, I choose you.',
  'I love how our hearts talk even when we are quiet. A small look, a little smile, a gentle touch — and I know exactly what you are feeling. That is our kind of magic.',
  'Thank you for being patient with me, for believing in me and for loving me through every version of myself. I promise to do the same for you, forever.',
  'My love for you is the one thing in my life I never have to question. It is steady, it is strong, and it is yours — today, tomorrow and for all the days to come.',
  'If happiness had a face, it would look like you laughing. If peace had a sound, it would be your voice. If love had a name, it would be yours.',
  'You are the dream I had before I even knew how to dream. Now that you are here, real and beside me, I promise to cherish you for the rest of my life.',
  'No matter what happens in this crazy world, please never forget this: you are the best thing that ever happened to me, and I will love you until my very last breath.',
];

/** Days since 1970 for the local date — changes at local midnight. */
export function dayNumber(d = new Date()) {
  return Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / 86_400_000);
}

/** Same note all day, a different one tomorrow. */
export function noteOfTheDay(d = new Date()) {
  return LOVE_NOTES[dayNumber(d) % LOVE_NOTES.length];
}
